package com.lukebu.ability;

public enum AbilityType {

    /*ABILITY METAL*/
    METALLURGY,
    ARMORSMITH,
    WEAPONSMITH,

    /*ABILITY WOOD */
    JOINERY, //PRACE STOLARSKIE
    CARPENTERING, //CIEŚLA
    WOODWORKING, //OBRÓBKA DREWNA

    /*ABILITY STONE */
    STONECUTTING, //KAMIENIARSTWO
    MASONRY, // MURARSTWO
    SCULPTURE, //RZEŹBIARSTWO

    /*ABILITY GATHERING*/
    OREMINING,  //WYDOBYCIE RUDY
    STONEMINING, //WYDOBYCIE KAMIENIA
    WOODCUTTING, //SCINANIE DRZEW
    HUNTING, //POLOWANIE
    FISHING, //ŁOWIENIE RYB
    CROPSHARVESTING, //UPRAWA ROŚLIN
    HERBSGATHERING, // ZBIERANIE ZIÓŁ

    /*ABILITY FOOD*/
    SEEDING,  //UPRAWA
    BUTCHER, // RZEŹNIK
    BREEDING, //HODOWLA ZWIERZĄT

    /*ABILITY LEATHER*/
    TANNING, //GARBOWANIE
    LEATHERARMORY,

    /*ABILITY TAILORING*/
    SPINNING, //PRZĘDZENIE
    WEAVING, //TKANIE
    SEWING, //SZYCIE

    /*ABILITY KNOWLEDGE */
    ALCHEMY,  //ALCHEMIA
    ENGINEERING, //INŻYNIERIA
    SCIENCE; //NAUKA

}
